# Generated by Django 2.0.7 on 2018-08-14 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_article', '0002_auto_20180814_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
