# Generated by Django 2.0.7 on 2018-08-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_article', '0003_auto_20180814_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
